"""add email verification fields

Revision ID: 4b8c011c25c1
Revises: ed547c32fd6b
Create Date: 2026-05-16 23:18:07.423435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b8c011c25c1'
down_revision = 'ed547c32fd6b'
branch_labels = None
depends_on = None


def upgrade():
    # Add email_verified with server_default=True so existing users are not locked out.
    # New signups will get False from the model's Python-side default.
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(),
                                       nullable=False, server_default=sa.text('true')))
        batch_op.add_column(sa.Column('email_verify_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('email_verify_expiry', sa.DateTime(), nullable=True))

    # Remove the server default so the Python model default (False) takes over for new rows
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email_verified', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_verify_expiry')
        batch_op.drop_column('email_verify_token')
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
