"""Add growth plan tracker tables

Revision ID: 768730e141fb
Revises: 8d9ee83c7899
Create Date: 2026-06-02 00:57:41.287663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768730e141fb'
down_revision = '8d9ee83c7899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('growth_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_type', sa.String(length=50), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_growth_plan_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_growth_plan'))
    )
    with op.batch_alter_table('growth_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_growth_plan_user_id'), ['user_id'], unique=False)

    op.create_table('daily_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('checkboxes', sa.Text(), nullable=True),
    sa.Column('metrics', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['growth_plan.id'], name=op.f('fk_daily_log_plan_id_growth_plan')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_log')),
    sa.UniqueConstraint('plan_id', 'day_number', name='uq_daily_log_plan_day')
    )
    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_log_plan_id'), ['plan_id'], unique=False)

    op.create_table('interview_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('round_name', sa.String(length=100), nullable=True),
    sa.Column('questions_asked', sa.Text(), nullable=True),
    sa.Column('performance_rating', sa.Integer(), nullable=True),
    sa.Column('weak_areas', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('followup_required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['growth_plan.id'], name=op.f('fk_interview_record_plan_id_growth_plan')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_record'))
    )
    with op.batch_alter_table('interview_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_record_plan_id'), ['plan_id'], unique=False)

    op.create_table('job_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('interview_date', sa.Date(), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('salary_offered', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['growth_plan.id'], name=op.f('fk_job_application_plan_id_growth_plan')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_application'))
    )
    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_application_plan_id'), ['plan_id'], unique=False)

    op.create_table('skill_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['growth_plan.id'], name=op.f('fk_skill_rating_plan_id_growth_plan')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_rating')),
    sa.UniqueConstraint('plan_id', 'skill_name', name='uq_skill_rating_plan_skill')
    )
    with op.batch_alter_table('skill_rating', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_rating_plan_id'), ['plan_id'], unique=False)

    op.create_table('topic_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=True),
    sa.Column('solved_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['growth_plan.id'], name=op.f('fk_topic_entry_plan_id_growth_plan')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topic_entry'))
    )
    with op.batch_alter_table('topic_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_entry_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_entry_plan_id'), ['plan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_entry_plan_id'))
        batch_op.drop_index(batch_op.f('ix_topic_entry_category'))

    op.drop_table('topic_entry')
    with op.batch_alter_table('skill_rating', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_rating_plan_id'))

    op.drop_table('skill_rating')
    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_application_plan_id'))

    op.drop_table('job_application')
    with op.batch_alter_table('interview_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_record_plan_id'))

    op.drop_table('interview_record')
    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_log_plan_id'))

    op.drop_table('daily_log')
    with op.batch_alter_table('growth_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_growth_plan_user_id'))

    op.drop_table('growth_plan')
    # ### end Alembic commands ###
