"""add file attachment model

Revision ID: 8d9ee83c7899
Revises: 5c9d3a4f8e2b
Create Date: 2026-05-21 07:31:27.157131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d9ee83c7899'
down_revision = '5c9d3a4f8e2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('discussion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussion.id'], name=op.f('fk_file_attachment_discussion_id_discussion')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_file_attachment_project_id_project')),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name=op.f('fk_file_attachment_task_id_task')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], name=op.f('fk_file_attachment_uploaded_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_attachment'))
    )
    with op.batch_alter_table('file_attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_attachment_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_attachment_discussion_id'), ['discussion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_attachment_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_attachment_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_attachment_uploaded_by'), ['uploaded_by'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_attachment_uploaded_by'))
        batch_op.drop_index(batch_op.f('ix_file_attachment_task_id'))
        batch_op.drop_index(batch_op.f('ix_file_attachment_project_id'))
        batch_op.drop_index(batch_op.f('ix_file_attachment_discussion_id'))
        batch_op.drop_index(batch_op.f('ix_file_attachment_created_at'))

    op.drop_table('file_attachment')
    # ### end Alembic commands ###
