"""add phase 3 collaboration

Revision ID: aa09266b3017
Revises: fca90576b188
Create Date: 2026-05-01 18:09:48.377279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa09266b3017'
down_revision = 'fca90576b188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_discussion_created_by_user')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_discussion_project_id_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discussion'))
    )
    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discussion_project_id'), ['project_id'], unique=False)

    op.create_table('discussion_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('discussion_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_discussion_comment_created_by_user')),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussion.id'], name=op.f('fk_discussion_comment_discussion_id_discussion')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discussion_comment'))
    )
    with op.batch_alter_table('discussion_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discussion_comment_discussion_id'), ['discussion_id'], unique=False)

    op.create_table('task_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_task_comment_created_by_user')),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name=op.f('fk_task_comment_task_id_task')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_comment'))
    )
    with op.batch_alter_table('task_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_comment_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_comment_task_id'))

    op.drop_table('task_comment')
    with op.batch_alter_table('discussion_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discussion_comment_discussion_id'))

    op.drop_table('discussion_comment')
    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discussion_project_id'))

    op.drop_table('discussion')
    # ### end Alembic commands ###
