"""add organizations

Revision ID: af0634824323
Revises: 607e76a63983
Create Date: 2026-05-01 00:31:54.075965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af0634824323'
down_revision = '607e76a63983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('invite_code', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_organization_created_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization')),
    sa.UniqueConstraint('name', name=op.f('uq_organization_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_organization_slug'))
    )
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_invite_code'), ['invite_code'], unique=True)

    op.create_table('org_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_org_member_org_id_organization')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_org_member_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_org_member')),
    sa.UniqueConstraint('org_id', 'user_id', name='uq_org_member')
    )
    with op.batch_alter_table('org_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_member_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_org_member_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('org_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_member_user_id'))
        batch_op.drop_index(batch_op.f('ix_org_member_org_id'))

    op.drop_table('org_member')
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_invite_code'))

    op.drop_table('organization')
    # ### end Alembic commands ###
