"""add projects and task assignments

Revision ID: fca90576b188
Revises: af0634824323
Create Date: 2026-05-01 07:45:27.414564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fca90576b188'
down_revision = 'af0634824323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_project_created_by_user')),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_project_org_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project'))
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_org_id'), ['org_id'], unique=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assigned_to', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_task_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_project_id'), ['project_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_task_assigned_to_user'), 'user', ['assigned_to'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_task_created_by_user'), 'user', ['created_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_task_project_id_project'), 'project', ['project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_task_project_id_project'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_task_created_by_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_task_assigned_to_user'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_task_project_id'))
        batch_op.drop_index(batch_op.f('ix_task_assigned_to'))
        batch_op.drop_column('created_by')
        batch_op.drop_column('assigned_to')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_org_id'))

    op.drop_table('project')
    # ### end Alembic commands ###
